version: "3"

services:
  prometheus:
    restart: always
    depends_on: []
    image: prom/prometheus:v2.30.2
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      # Permits `curl --request POST http://localhost:9090/-/reload`
      - --web.enable-lifecycle
      - --log.level=debug
    volumes:
      - ${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml
    expose:
      - "9090"
    ports:
      - 9090:9090

  prom-oauth-proxy:
    restart: always
    depends_on:
    - prometheus
    image: ghcr.io/dazwilkin/prometheus-oauth-proxy:109cb7aa6c964cfa08d3de9687509808cf29f2f2
    container_name: prom-oauth-proxy
    command:
      - target_url=https://ackal-healthcheck-server-2eynp5ydga-wl.a.run.app
      - port=7777
    environment:
      API_KEY: ${API_KEY}
      GOOGLE_APPLICATION_CREDENTIALS: /secrets/client_secret.json
    volumes:
    - ${PWD}/client_secret.json:/secrets/client_secret.json
    expose:
    - "7777"
    ports:
    - 7777:7777
