version: "3"

services:
  prometheus:
    restart: always
    depends_on: []
    image: prom/prometheus:v2.30.2
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-lifecycle
      # - --log.level=debug
    volumes:
      - ${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml
    expose:
      - "9090"
    ports:
      - 9090:9090

  gcp-oidc-token-proxy:
    restart: always
    depends_on:
    - prometheus
    image: ghcr.io/dazwilkin/gcp-oidc-token-proxy:1e481c723cec01e4f6b71a88a74d62364a33e5fe
    container_name: gcp-oidc-token-proxy
    command:
      - --target_url=https://some-service-xxxxxxxxxx-xx.a.run.app
      - --port=7777
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /secrets/key.json
    volumes:
    - ${PWD}/key.json:/secrets/key.json
    expose:
    - "7777"
    ports:
    - 7777:7777
