version: "3"

services:
  prometheus:
    restart: always
    depends_on: []
    image: prom/prometheus:v2.30.2
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-lifecycle
      # - --log.level=debug
    volumes:
      - ${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml
    expose:
      - "9090"
    ports:
      - 9090:9090

  gcp-oidc-token-proxy:
    restart: always
    depends_on:
    - prometheus
    image: ghcr.io/dazwilkin/gcp-oidc-token-proxy:a88e720e21dc7f66d3d1435b113731e8be36daca
    container_name: gcp-oidc-token-proxy
    command:
      - --target_url=https://some-server-xxxxxxxxxx-xx.a.run.app
      - --port=7777
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /secrets/client_secret.json
    volumes:
    - ${PWD}/client_secret.json:/secrets/client_secret.json
    expose:
    - "7777"
    ports:
    - 7777:7777
