version: "3"

services:
  prometheus:
    restart: always
    depends_on: []
    image: docker.io/prom/prometheus:v2.30.2
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-lifecycle
      # - --log.level=debug
    volumes:
      - ${PWD}/prometheus.yml:/etc/prometheus/prometheus.yml
    expose:
      - "9090"
    ports:
      - 9090:9090

  gcp-oidc-token-proxy:
    restart: always
    depends_on:
    - prometheus
    image: ghcr.io/dazwilkin/gcp-oidc-token-proxy:b9dfac3a2adc8afbfe30b7d0df7d5309eea32cae
    container_name: gcp-oidc-token-proxy
    command:
      - --port=7777
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /secrets/key.json
    volumes:
    - ${PWD}/ACCOUNT.json:/secrets/key.json
    expose:
    - "7777"
    ports:
    - 7777:7777
  