global:
  scrape_interval: 1m
  evaluation_interval: 1m

scrape_configs:
  # Self
  - job_name: "prometheus-server"
    static_configs:
      - targets:
          - "localhost:9090"

  # Prometheus OAuth Token Proxy
  # - job_name: "prom-oauth-proxy"
  #   static_configs:
  #   - targets:
  #     - "prom-oauth-proxy"

  # Cloud Run Healthcheck service
  - job_name: "healthcheck-server"
    scheme: https
    oauth2:
      client_id: "foo"
      client_secret: "bar"
      scopes:
      - "https://www.googleapis.com/auth/cloud-platform"
      token_url: "http://prom-oauth-proxy:7777/"
    static_configs:
      - targets:
          - "ackal-healthcheck-server-2eynp5ydga-wl.a.run.app:443"

  # cAdvisor exports metrics for *all* containers running on this host
  - job_name: cadvisor
    static_configs:
      - targets:
          - "cadvisor:8080"

  # Node Exporter
  - job_name: node-exporter
    static_configs:
      - targets:
          - "node-exporter:9100"