global:
  scrape_interval: 5m
  # evaluation_interval: 5m

scrape_configs:
  # Self
  - job_name: "prometheus"
    static_configs:
      - targets:
          - "localhost:9090"

  # GCP OAuth Token Proxy
  - job_name: "gcp-oidc-token-proxy"
    static_configs:
    - targets:
      - "localhost:7777"

  # Cloud Run service
  - job_name: "cloudrun-service"
    scheme: https
    oauth2:
      client_id: "anything"
      client_secret: "anything"
      token_url: "http://localhost:7777"
      endpoint_params:
        audience: "https://some-service-xxxxxxxxxx-xx.a.run.app"
    static_configs:
      - targets:
          - "some-service-xxxxxxxxxx-xx.a.run.app:443"
